---
- hosts: production_server
  become: yes # Run as root
  tasks:
  - name: Install necessary packages
    apt:
      name: "{{ packages }}" # The module defined below
      state: latest
    vars:
      packages: # List of packages to install
      - openjdk-17-jdk
      - maven

  - name: Clone Petclinic repository
    git:
      repo: 'https://github.com/mimikuo365/spring-petclinic.git'
      dest: '/home/mimi/spring-petclinic'
      clone: yes
      update: yes

  - name: Build Petclinic using Maven
    shell: sudo ./mvnw package -DskipTests
    args:
      chdir: '/home/mimi/spring-petclinic' # Change directory to the cloned repository

  - name: Run Petclinic
    shell: nohup java -Dserver.port=8000 -jar target/*.jar &
    args:
      chdir: '/home/mimi/spring-petclinic'
